<?php
namespace braga\daogenerator\generator;
/**
 * Created on 18 cze 2016 19:38:04
 * error prefix
 * @author Tomasz Gajewski
 * @package
 *
 */
class PostgreDAOFileGenerator extends DAOFileGenerator
{
	// ------------------------------------------------------------------------------------------------------------------
	protected function generateCreate(Table $t)
	{
		$data = array();
		$pk = array();
		foreach($t->getColumny() as $column)
		{
			if($column->isPK())
			{
				$pk[$column->getKey()] = $column;
				if(!$column->isAutoGenerated())
				{
					$data[$column->getKey()] = $column;
				}
			}
			else
			{
				$data[$column->getKey()] = $column;
			}
		}

		$this->addLine("/**", 1);
		$this->addLine(" * Methods add object of class " . $t->getClassName(), 1);
		$this->addLine(" * insert record into table " . $t->getName(), 1);
		$this->addLine(" * @throws ExecutionSqlException", 1);
		$this->addLine(" * @throws \\Throwable", 1);
		$this->addLine(" * @throws \\braga\\db\\exception\\GeneralSqlException", 1);
		$this->addLine(" * @return bool", 1);
		$this->addLine(" */", 1);
		$this->addLine("protected function create(): bool", 1);
		$this->addLine("{", 1);
		$this->addLine("\$db = new DB();", 2);
		$this->addLine("\$sql = <<<SQL", 2);

		$columns = array();
		$params = array();
		foreach($data as $column)
		{
			$columns[$column->getName()] = $column->getName();
			$params[$column->getName()] = preg_replace("/[^A-Z1-9]/", "", strtoupper($column->getName()));
			if(strlen($params[$column->getName()]) == 0)
			{
				$params[$column->getName()] = RandomStringLetterOnly(8);
			}
		}
		$this->addLine("INSERT INTO {$t->getName()} (" . implode(", ", $columns) . ") ", 3);
		$this->addLine("VALUES (:" . implode(", :", $params) . ") ", 3);

		$this->addLine("SQL;", 3);
		$pkSequenced = false;
		if(count($pk) == 1)
		{
			if(current($pk)->isAutoGenerated())
			{
				$pkSequenced = true;
				$this->addLine("\$sql .= \"RETURNING * \";", 2);
			}
		}

		foreach($data as $column)
		{
			if($column->getType() == ColumnType::BLOB)
			{
				$this->addLine("\$db->setParam(\"" . $params[$column->getName()] . "\", \$this->get" . ucfirst($column->getClassFieldName()) . "(), \PDO::PARAM_LOB);", 2);
			}
			else
			{
				$this->addLine("\$db->setParam(\"" . $params[$column->getName()] . "\", \$this->get" . ucfirst($column->getClassFieldName()) . "());", 2);
			}
		}
		$this->addLine("\$db->query(\$sql);", 2);
		$this->addLine("if(1 == \$db->getRowAffected())", 2);
		$this->addLine("{", 2);
		if($pkSequenced)
		{
			$this->addLine("\$this->set" . ucfirst(current($pk)->getClassFieldName()) . "(\$db->getLastInsertID());", 3);
		}
		$this->addLine("self::updateFactoryIndex(\$this);", 3);
		$this->addLine("\$this->setReaded();", 3);
		$this->addLine("return true;", 3);
		$this->addLine("}", 2);
		$this->addLine("else", 2);
		$this->addLine("{", 2);
		$this->addLine("throw new \\braga\\db\\exception\\ExecutionSqlException(\$db, \"" . $t->getErrorPrefix() . "02 Insert record into table " . $t->getName() . " fail\");", 3);
		$this->addLine("}", 2);
		$this->addLine("}", 1);
		$this->addLine("// -----------------------------------------------------------------------------------------------------------------", 1);
	}
	// ------------------------------------------------------------------------------------------------------------------
}
